config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin } { mount Sidekiq::Web => '/sidekiq' }

  namespace :admin do
    resources :users
    resources :guests
    resources :businesses do
      get :export_bookings, on: :member
    end
    resources :bowlings
    resources :laser_tags
    resources :lanes
    resources :rooms
    resources :orders
    resources :bookings

    root to: "users#index"
  end

  namespace :report do
    resources :businesses, only: [:index]
  end

  root 'welcome#index'
  devise_for :users

  resources :businesses, except: [:destroy], shallow: true do
    resources :activities, only: [:index, :new, :create, :edit, :update, :destroy] do
      get :view_analytics, on: :member
      resources :reservables, only: [:new, :create,  :edit, :update, :destroy]
      resources :closed_schedules, only: [:index, :create]
      resources :rate_override_schedules, only: [:index, :create]
    end
  end

  resources :orders, only: [:new, :create] do
    get :success, on: :member
  end
  post 'reserver_order', to: 'orders#reserver_order'
  resources :users, only: [:show, :edit, :update]
  resources :closed_schedules, only: [:destroy]
  resources :rate_override_schedules, only: [:destroy]
  patch 'bookings/:id/check_in', to: 'bookings#check_in', as: 'booking_check_in'
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: 'booking_cancel'

  get 'prepare_complete_order', to: 'orders#prepare_complete_order'
  get 'get_order_prices', to: 'orders#get_order_prices'
  get 'check_payment_requirement', to: 'orders#check_payment_requirement'
  get 'activities/search', to: 'activities#search'
  get 'search', to: 'search#search'
  get 'search/paginate_reservables', to: 'search#paginate_reservables'
  get 'activities/:activity_id/reservations',
    to: 'orders#reservations_for_business_owner', as: 'business_owner_reservations'
  get 'activities/:activity_id/reserver',
    to: 'orders#reserver', as: 'business_owner_reserver'
  get 'users/:user_id/reservations', to: 'orders#reservations_for_users',
    as: 'user_reservations'
end

app/views/layouts/shared/_alert.html.erb
<%- [:notice, :info, :warning, :error, :alert].each do |kind| -%>
  <%- next if flash[kind].blank? -%>
  <%
    alert_type = case kind
      when :notice
        'success'
      when :error
        'danger'
      when :info
        'info'
      when :warning, :alert
        'warning'
      end
  %>
  <div class="container">
    <div class="alert alert-dismissable alert-<%= alert_type %> notice fade in" role="alert">
      <button class="close" data-dismiss="alert" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= flash[kind] %>
    </div>
  </div>
<%end%>

app/views/layouts/shared/_facebook_share_button_script.html.erb
<div id="fb-root">
</div>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
    js.src += "&appId=<%= ENV.fetch('FACEBOOK_APP_ID') %>"
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-fixed-top bg-faded">
  <%= link_to(root_path, class: 'navbar-brand', id: 'openplay-logo') do %>
    <%= image_tag('logo') %>
  <% end %>

  <% if user_signed_in? %>
    <div class="btn-group pull-xs-right">
      <button type="button" class="btn dropdown-toggle nav-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.email %>
      </button>
      <div class="dropdown-menu dropdown-menu-right">
        <% if manages_business? %>
          <%= link_to('Your Business Info', current_user.business,
            class: 'nav-link dropdown-item') %>
        <%end%>
        <%= link_to('Your Bookings', user_reservations_path(current_user), class: 'nav-link dropdown-item') %>
        <%= link_to('Your Profile', user_path(current_user), class: 'nav-link dropdown-item') %>
        <%= link_to('Log Out', destroy_user_session_path, method: :delete, class: 'nav-link dropdown-item') %>
      </div>
    </div>

    <% if policy(Order).manage? %>
      <ul class="nav navbar-nav">
        <li class="nav-item pull-xs-right">
          <%= link_to 'Reports', report_businesses_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>

    <% if manages_business? %>
      <ul class="nav navbar-nav">
        <li class="nav-item pull-xs-right">
          <%= link_to 'Manage Business', business_activities_path(current_user.business), class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  <% else %>
    <ul class="nav navbar-nav">
      <li class="nav-item pull-xs-right">
        <%= link_to('Sign In', new_user_session_path, class: 'nav-link') %>
      </li>
      <li class="nav-item pull-xs-right">
        <%= link_to('Sign Up', new_user_registration_path, class: 'nav-link') %>
      </li>
      <li class="nav-item pull-xs-right">
        <%= link_to 'About Us', 'https://www.site.openplay.io/about',
          class: 'nav-link' %>
      </li>
    </ul>

  <% end %>
</nav>

app/views/layouts/shared/_twitter_share_button_script.html.erb
<script>
  window.twttr = (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0],
      t = window.twttr || {};
    if (d.getElementById(id)) return t;
    js = d.createElement(s);
    js.id = id;
    js.src = "https://platform.twitter.com/widgets.js";
    fjs.parentNode.insertBefore(js, fjs);

    t._e = [];
    t.ready = function(f) {
      t._e.push(f);
    };
    return t;
  }(document, "script", "twitter-wjs"));
</script>