config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin } { mount Sidekiq::Web => '/sidekiq' }

  namespace :admin do
    resources :users
    resources :guests
    resources :businesses do
      get :export_bookings, on: :member
    end
    resources :bowlings
    resources :laser_tags
    resources :lanes
    resources :rooms
    resources :orders
    resources :bookings

    root to: "users#index"
  end

  namespace :report do
    resources :businesses, only: [:index]
  end

  root 'welcome#index'
  devise_for :users

  resources :businesses, except: [:destroy], shallow: true do
    resources :activities, only: [:index, :new, :create, :edit, :update, :destroy] do
      get :view_analytics, on: :member
      resources :reservables, only: [:new, :create,  :edit, :update, :destroy]
      resources :closed_schedules, only: [:index, :create]
      resources :rate_override_schedules, only: [:index, :create]
    end
  end

  resources :orders, only: [:new, :create] do
    get :success, on: :member
  end
  post 'reserver_order', to: 'orders#reserver_order'
  resources :users, only: [:show, :edit, :update]
  resources :closed_schedules, only: [:destroy]
  resources :rate_override_schedules, only: [:destroy]
  patch 'bookings/:id/check_in', to: 'bookings#check_in', as: 'booking_check_in'
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: 'booking_cancel'

  get 'prepare_complete_order', to: 'orders#prepare_complete_order'
  get 'get_order_prices', to: 'orders#get_order_prices'
  get 'check_payment_requirement', to: 'orders#check_payment_requirement'
  get 'activities/search', to: 'activities#search'
  get 'search', to: 'search#search'
  get 'search/paginate_reservables', to: 'search#paginate_reservables'
  get 'activities/:activity_id/reservations',
    to: 'orders#reservations_for_business_owner', as: 'business_owner_reservations'
  get 'activities/:activity_id/reserver',
    to: 'orders#reserver', as: 'business_owner_reserver'
  get 'users/:user_id/reservations', to: 'orders#reservations_for_users',
    as: 'user_reservations'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    current_user&.update_session_location(location_params)
    @booking_date = params[:booking_date]
    redirect_to root_path,
      alert: 'Date is required.' and return true unless @booking_date.present?
    @booking_time = params[:booking_time]
    @activities = Activity.search_by_type_within_area(
      location_params.merge(date: @booking_date)
    )
  end

  def paginate_reservables
    @booking_date = params[:booking_date]
    @booking_time = params[:booking_time]
    @activity = Activity.find(params[:activity_id])
    @reservables = @activity.reservables.active.order(:name).page(params[:page]).per(5)
    respond_to do |format|
      format.js
    end
  end

  private

  def location_params
    params.permit(:address, :latitude, :longitude, :activity_type)
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def first_set_of_reservables(reservables)
    reservables.active.order(:name).page(1).per(5)
  end
end

app/views/search/_activity_booking_pane.html.erb
<div class="row">
  <% activity.reservables.each do |reservable| %>
    <div class='alert alert-success reservable-popup' id="<%= "popup-#{activity.id}-#{reservable.id}" %>" role='alert' >
  </div>
<% end %>
</div>
<div class="row activity-result">
  <div class="col-xs-12">
    <% if show_business_tile %>
      <div class="col-xs-3">
        <div class="activity-preview">
          <%= render 'businesses/info_tile', business: activity.business %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-9">
      <%= form_tag(new_order_path, method: :get) do %>
        <div class="col-xs-9">
          <div class="activity-info">
            <span class='activity-name'><%= activity.name %></span>
            <div class='reservables'>
              <div class="spinner">
                <div class="spinner-icon">
                </div>
              </div>
              <% @reservables = first_set_of_reservables(activity.reservables) %>
              <div class="timeslots activity-<%= activity.id %>">
                <%= render 'search/pagination', activity_id: activity.id %>
              </div>
            </div>
          </div>
        </div>

        <%= hidden_field_tag('date', @booking_date) %>
        <%= hidden_field_tag("prevent-btb-booking-#{activity.id}",
          activity.prevent_back_to_back_booking) %>
        <%= hidden_field_tag('activity_id', activity.id) %>
        <div class="col-xs-2 book-section">
          <%= submit_tag 'Book', class: 'btn btn-info book-btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/search/_pagination.html.erb
<% @reservables.each do |reservable| %>
  <%= render 'search/reservable', reservable: reservable %>
<% end %>
<% if @reservables.total_pages > 1 %>
  <div class='pagination'>
    <%= link_to 'Previous', search_paginate_reservables_path(
      activity_id: activity_id,
      booking_date: @booking_date,
      booking_time: @booking_time,
      page: @reservables.current_page - 1
    ), class: 'prev', remote: true unless @reservables.first_page? %>
    <div class='page-of'>
      <%= "Page #{@reservables.current_page} of #{@reservables.total_pages}" %>
    </div>
    <%= link_to 'Next', search_paginate_reservables_path(
      activity_id: activity_id,
      booking_date: @booking_date,
      booking_time: @booking_time,
      page: @reservables.current_page + 1
    ), class: 'next', remote: true unless @reservables.last_page? %>
  </div>
<% end %>

app/views/search/_reservable.html.erb
<div class="reservable" id='<%= "reservable_#{reservable.id}" %>'>
  <div class='card'>
    <div class='card-block'>
      <h5 class="card-title reservable-name"><%= reservable.name %></h5>
      <% if max_players =  maximum_players(reservable) %>
        <h6 class='card-subtitle text-muted'>
          Max <%= max_players %> people per reservation
        </h6>
      <% end %>
      <p class='card-text'><%= reservable.description %></p>
      <div class="row-times" data-slick='{"initialSlide":
        <%= requested_time_slot_index(reservable, @booking_date, @booking_time) %>}'>
        <% i = 0 %>
        <% build_time_slots(reservable, @booking_date).each do |slot| %>
          <div>
            <% booking_id = slot[:booking_info][:booking_id] %>
            <%= button_tag(type: 'button', class: 'btn btn-danger btn-3d timeslot ' +
              booked_by_current_user(slot) + booking_classes(slot[:booking_info]),
              data: {
                activity_id: reservable.activity_id,
                reservable_id: reservable.id,
                interval: reservable.interval,
                selected_reservable: reservable.name,
                slot: i+=1,
                checkin_path: booking_id ? booking_check_in_path(booking_id) : nil,
                cancel_path: booking_id ? booking_cancel_path(booking_id) : nil
              },
              id: "timeslot-#{reservable.activity_id}-#{reservable.id}-#{i}",
              disabled: !slot[:booking_info][:available] && !request.path.match('reserver')) do %>
                <%= slot[:time].strftime("%H:%M") %>
            <% end %>
            <%= check_box_tag 'time_slots[' + reservable.id.to_s + '][]',
              "#{slot[:time].strftime("%H:%M")},#{(slot[:time] +
              reservable.interval.minutes).strftime("%H:%M")}",
              false, class: 'checkbox-hidden',
              id: "#{reservable.activity_id}-#{reservable.id}-#{i}" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/paginate_reservables.js.erb
$('.activity-<%=@activity.id%>').html("<%= escape_javascript (render partial: 'search/pagination', locals: {activity_id: @activity.id}) %>");
Utilities.preventBackToBackBooking();
Utilities.slidingSlot();
Utilities.hideSpinner();

app/views/search/search.html.erb
<% if @activities.empty? %>
  <h4> No results found. </h4>
<% else %>
  <div class="activity-list">
    <% @activities.each do |activity| %>
      <%= render 'activity_booking_pane', activity: activity,
        show_business_tile: true %>
    <% end %>
  </div>
<% end %>