config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin } { mount Sidekiq::Web => '/sidekiq' }

  namespace :admin do
    resources :users
    resources :guests
    resources :businesses do
      get :export_bookings, on: :member
    end
    resources :bowlings
    resources :laser_tags
    resources :lanes
    resources :rooms
    resources :orders
    resources :bookings

    root to: "users#index"
  end

  namespace :report do
    resources :businesses, only: [:index]
  end

  root 'welcome#index'
  devise_for :users

  resources :businesses, except: [:destroy], shallow: true do
    resources :activities, only: [:index, :new, :create, :edit, :update, :destroy] do
      get :view_analytics, on: :member
      resources :reservables, only: [:new, :create,  :edit, :update, :destroy]
      resources :closed_schedules, only: [:index, :create]
      resources :rate_override_schedules, only: [:index, :create]
    end
  end

  resources :orders, only: [:new, :create] do
    get :success, on: :member
  end
  post 'reserver_order', to: 'orders#reserver_order'
  resources :users, only: [:show, :edit, :update]
  resources :closed_schedules, only: [:destroy]
  resources :rate_override_schedules, only: [:destroy]
  patch 'bookings/:id/check_in', to: 'bookings#check_in', as: 'booking_check_in'
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: 'booking_cancel'

  get 'prepare_complete_order', to: 'orders#prepare_complete_order'
  get 'get_order_prices', to: 'orders#get_order_prices'
  get 'check_payment_requirement', to: 'orders#check_payment_requirement'
  get 'activities/search', to: 'activities#search'
  get 'search', to: 'search#search'
  get 'search/paginate_reservables', to: 'search#paginate_reservables'
  get 'activities/:activity_id/reservations',
    to: 'orders#reservations_for_business_owner', as: 'business_owner_reservations'
  get 'activities/:activity_id/reserver',
    to: 'orders#reserver', as: 'business_owner_reserver'
  get 'users/:user_id/reservations', to: 'orders#reservations_for_users',
    as: 'user_reservations'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'public'

  def index
    if current_user&.should_reset_session_location?
      current_user.update_session_location # Set session location to nil
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div id="hero-container">
  <div id="hero-background-image"></div>
  <div id="hero-content">
    <h1 class="text-xs-center shadow">Making Family Fun Easy!</h1>
    <h1 class="text-xs-center">Making Family Fun Easy!</h1>
    <div class="text-xs-center" id="searchbar-container">
      <div class="row">
        <%= form_tag(search_path, method: 'get') do %>
          <div class="container">
            <div class="col-sm-2">
              <input type='text' id='datepicker', name='booking_date', class='form-control'>
            </div>
            <div class="col-sm-2">
              <input type='text' id='timepicker', name='booking_time', class='form-control'>
            </div>
            <div class="col-sm-3">
              <%= select_tag('activity_type', options_for_select(
                Activity.types.collect {|t| [t.humanize, t.camelcase]}),
              class: 'form-control') %>
            </div>
            <div class="col-sm-3">
              <%= text_field_tag nil, nil, data: {key: ENV['GOOGLE_API_KEY']},
                  class: 'form-control autocomplete-places',
                  placeholder: 'Location' %>
              <%= hidden_field_tag 'address', current_user&.current_address,
                  class: 'place-address' %>
              <%= hidden_field_tag 'latitude', current_user&.current_latitude,
                  class: 'place-latitude' %>
              <%= hidden_field_tag 'longitude', current_user&.current_longitude,
                  class: 'place-longitude' %>
            </div>
            <div class="col-sm-2">
              <%= submit_tag('Search', class: 'btn btn-default btn-block') %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div id='discovery-tiles'>
    <div class="row">
      <div class='col-sm-4'>
        <%= image_tag "bowling_feature", class: 'img-fluid' %>
        <!-- <a class="btn btn&#45;default btn&#45;block" data&#45;activity="Bowling" href="#"> -->
        <!--   See Bowling Times -->
        <!-- </a> -->
      </div>
      <div class='col-sm-4'>
        <%= image_tag "lasertag_feature", class: 'img-fluid' %>
        <!-- <a class="btn btn&#45;default btn&#45;block" data&#45;activity="LaserTag" href="#"> -->
        <!--   See Laser Tag Times -->
        <!-- </a> -->
      </div>
      <div class='col-sm-4'>
        <%= image_tag "minigolf_feature", class: 'img-fluid' %>
        <!-- <a class="btn btn&#45;default btn&#45;block" href="#">Mini Golf Coming Soon!</a -->
      </div>
    </div>
  </div>
  <!-- <% if user_signed_in? && !manages_business? %>
    <div class="spacer-50"></div>
    <div class="jumbotron">
      <div class="container text-xs-center">
        <h3>Are you a business owner?</h3>
        <div class="lead">
          <p>Join us and manage your reservations with OpenPlay!</p>
          <%= link_to 'Join us', new_business_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %> -->
  <p class="text-xs-center copyright">Copyright <%= Time.now.year %> Open Play Enterprises, Inc.</p>
</div>