config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin } { mount Sidekiq::Web => '/sidekiq' }

  namespace :admin do
    resources :users
    resources :guests
    resources :businesses do
      get :export_bookings, on: :member
    end
    resources :bowlings
    resources :laser_tags
    resources :lanes
    resources :rooms
    resources :orders
    resources :bookings

    root to: "users#index"
  end

  namespace :report do
    resources :businesses, only: [:index]
  end

  root 'welcome#index'
  devise_for :users

  resources :businesses, except: [:destroy], shallow: true do
    resources :activities, only: [:index, :new, :create, :edit, :update, :destroy] do
      get :view_analytics, on: :member
      resources :reservables, only: [:new, :create,  :edit, :update, :destroy]
      resources :closed_schedules, only: [:index, :create]
      resources :rate_override_schedules, only: [:index, :create]
    end
  end

  resources :orders, only: [:new, :create] do
    get :success, on: :member
  end
  post 'reserver_order', to: 'orders#reserver_order'
  resources :users, only: [:show, :edit, :update]
  resources :closed_schedules, only: [:destroy]
  resources :rate_override_schedules, only: [:destroy]
  patch 'bookings/:id/check_in', to: 'bookings#check_in', as: 'booking_check_in'
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: 'booking_cancel'

  get 'prepare_complete_order', to: 'orders#prepare_complete_order'
  get 'get_order_prices', to: 'orders#get_order_prices'
  get 'check_payment_requirement', to: 'orders#check_payment_requirement'
  get 'activities/search', to: 'activities#search'
  get 'search', to: 'search#search'
  get 'search/paginate_reservables', to: 'search#paginate_reservables'
  get 'activities/:activity_id/reservations',
    to: 'orders#reservations_for_business_owner', as: 'business_owner_reservations'
  get 'activities/:activity_id/reserver',
    to: 'orders#reserver', as: 'business_owner_reserver'
  get 'users/:user_id/reservations', to: 'orders#reservations_for_users',
    as: 'user_reservations'
end

app/models/activity.rb
class Activity < ApplicationRecord
  include TimeValidations
  IMAGE_FORMATS = ['image/jpeg', 'image/jpg', 'image/png'].freeze

  belongs_to :business
  has_many :reservables, dependent: :destroy
  has_many :orders
  has_many :closed_schedules, dependent: :destroy
  has_many :rate_override_schedules, dependent: :destroy
  has_many :party_rooms, foreign_key: 'activity_id'

  has_attached_file :picture,
    url: ':s3_domain_url',
    path: 'activity/:id/:basename.:extension',
    default_url: 'avatar/:style/activity-avatar.png',
    storage: :s3,
    bucket: ENV['S3_BUCKET'],
    s3_credentials: {
      access_key_id: ENV['S3_KEY'],
      secret_access_key: ENV['S3_SECRET'],
    },
    s3_protocol: 'https',
    styles:  { medium: ['300x300>'], larger: '600x600#' }

  validates_attachment_content_type :picture, content_type: IMAGE_FORMATS,
    message: 'Uploaded file is not a valid image. Only JPG, JPEG and PNG files'\
             ' are allowed'
  validates :name, presence: true

  scope :active, -> { where(archived: false) }
  scope :by_type, ->(type) { where(type: type).active }
  scope :by_business, lambda { |business_id|
    where(business_id: business_id).active
  }
  scope :by_location, lambda { |lat, lng|
    return all if lat.blank? || lng.blank?
    where(business_id: Business.find_nearest_business(lat, lng).map(&:id))
  }
  scope :available_on_date, lambda { |date|
    days_from_now = (Date.parse(date) - Date.current).to_i
    where('lead_time <= ?', days_from_now)
  }

  delegate :user, to: :business
  delegate :id, to: :business, prefix: true

  def self.types
    %w(bowling laser_tag escape_room)
  end

  def self.search_by_type_within_area(query)
    by_type(query[:activity_type])
      .available_on_date(query[:date])
      .by_location(query[:latitude], query[:longitude])
  end

  def self.search_by_business(business_id, date)
    by_business(business_id)
      .available_on_date(date)
  end

  def build_reservable(type)
    reservable = case type
                 when 'Lane'
                   lanes.new
                 when 'Room'
                   rooms.new
                 when 'PartyRoom'
                   party_rooms.new
                 end
    reservable.start_time = start_time
    reservable.end_time = end_time
    reservable
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  include DateTimeHelper
  before_action :authenticate_user!
  before_action :set_business, only: [:index, :new, :create]
  before_action :set_activity, only: [:destroy, :edit, :update, :view_analytics]
  after_action :verify_authorized

  def index
    @activities = @business.activities.active.decorate
    authorize @business.activities.build
  end

  def new
    @activity = @business.activities.build
    authorize @activity
  end

  def create
    @activity = @business.activities.build(activity_params)
    authorize @activity
    if @activity.save
      redirect_to business_activities_path, notice: 'Successfully created activity'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @activity.update(activity_params)
      redirect_to business_activities_path(@activity.business),
        notice: 'Successfully updated activity'
    else
      render :edit
    end
  end

  def destroy
    if @activity.update(archived: true)
      redirect_back fallback_location: root_path, notice: 'Successfully deleted activity'
    else
      flash[:error] = 'Unable to delete activity'
      redirect_back fallback_location: root_path
    end
  end

  def view_analytics
    bookings = Booking.belongs_to_activity(@activity)
    booking_data = bookings.revenues_by_date_in_60_days
    @booking_dates = booking_data.collect { |key,value|
      present_date_in_day_month_year_format(key)
    }
    @booking_revenues = booking_data.values
  end

  private

  def set_activity
    @activity = Activity.find_by_id(params[:id])
    authorize @activity
  end

  def set_business
    @business = Business.find(params[:business_id])
  end

  def activity_params
    permitted_params = %i[
      name
      picture
      description
      start_time
      end_time
      type
      prevent_back_to_back_booking
      allow_multi_party_bookings
      lead_time
    ]
    params.require(:activity).permit(permitted_params)
  end
end

app/controllers/admin/activities_controller.rb
module Admin
  class ActivitiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Activity.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Activity.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def should_activate_edit_activity?(controller_name, action_name)
    'active' if controller_name == 'activities' &&
    (action_name == 'edit' || action_name == 'update')
  end

  def should_activate_closing_time_schedules?(controller_name, action_name)
    'active' if controller_name == 'closed_schedules' &&
    (action_name == 'index' || action_name == 'create')
  end

  def should_activate_rate_override_schedules?(controller_name, action_name)
    'active' if controller_name == 'rate_override_schedules' &&
    (action_name == 'index' || action_name == 'create')
  end
end

app/views/activities/_activity_form.html.erb
<%= form_for @activity, as: :activity,
  url: { action: @activity.persisted? ? 'update' : 'create' } do |f| %>

  <%- unless @activity.persisted? %>
    <div class="form-group row">
      <div class="col-xs-2">
        <%= f.label :type %>
      </div>
      <div class="col-xs-10">
        <%= f.select :type, Activity.types.collect {|t| [t.humanize, t.camelcase]},
          {}, { class: 'form-control' } %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-xs-2">
      <%= f.label :name %>
    </div>
    <div class="<%= ('has-danger' if @activity.errors[:name].any?) %> col-xs-10">
      <%= f.text_field :name, placeholder: 'Activity name', class: 'form-control' %>
      <% @activity.errors[:name].each do |error| %>
        <div class="form-control-feedback">
          <%= error %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="<%= ('has-danger' if @activity.errors[:picture].any?) %> form-group row">
    <div class="col-xs-2">
      <%= f.label :picture %>
    </div>
    <div class='col-xs-10'>
      <%= f.file_field :picture, placeholder: 'Picture', class: 'form-control' %>
      <div class='form-control-feedback'>
        <%= @activity.errors[:picture].last %>
      </div>
    </div>
  </div>
  
  <div class='form-group row'>
    <div class='col-xs-2'>
      <%= f.label :description, nil, class: 'col-form-label' %>
    </div>
    <div class='col-xs-10'>
      <%= f.text_area :description, class: 'form-control', rows: 5 %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-xs-2">
      <%= f.label :start_time, class: 'col-form-label' %>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :start_time, value: "#{present_time(f.object.start_time)}",
        class: 'form-control'%>
    </div>

    <div class="col-xs-2">
      <%= f.label :end_time, class: 'col-form-label' %>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :end_time, value: "#{present_time(f.object.end_time)}",
        class: 'form-control'%>
    </div>

    <% if @activity.errors[:end_time].any? %>
      <div class="has-danger col-xs-12">
        <div class="row">
          <div class="col-xs-4 offset-xs-8">
            <% @activity.errors[:end_time].each do |error| %>
              <div class="form-control-feedback">
                <%= error %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="form-group row">
    <div class="col-xs-2">
      <%= f.label :lead_time, 'Lead time(days)' %>
    </div>
    <div class="col-xs-10">
      <%= f.number_field :lead_time, min: 0 %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-xs-12">
      <%= f.label :prevent_back_to_back_booking, 'Prevent back-to-back bookings:' %>
      <%= f.check_box :prevent_back_to_back_booking %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-xs-12">
      <%= f.label :allow_multi_party_bookings, 'Allow multi-party bookings:' %>
      <%= f.check_box :allow_multi_party_bookings %>
    </div>
  </div>

  <div class="from-group row">
    <div class="col-xs-12">
      <center>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </center>
    </div>
  </div>
<% end %>

app/views/activities/_activity_tab.html.erb
<div class="row">
  <div class="col-xs-12">
    <center>
      <h1>Edit Activity</h1>
    </center>
  </div>
</div>
<div class="spacer-40"></div>
<div class="row">
  <div class="col-xs-12">
    <%= render 'activities/activity_form' %>
  </div>
</div>
<br>
<%= render 'activities/reservables_form' %>

app/views/activities/_reservables_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <thead>
        <tr>
          <th><%=@activity.reservable_type%></th>
          <th>Interval</th>
          <th>Start time</th>
          <th>End time</th>
          <th>Maximum players</th>
          <th>Weekday price</th>
          <th>Weekend price</th>
          <th>Per Person Weekday Price</th>
          <th>Per Person Weekend Price</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @activity.reservables.active.each do |reservable| %>
          <tr class='<%= "reservable_#{reservable.id}" %>'>
            <td><%= reservable.name %></td>
            <td><%= reservable.interval %></td>
            <td><%= present_time(reservable.start_time)%></td>
            <td><%= present_time(reservable.end_time)%></td>
            <td><%= reservable.maximum_players %></td>
            <td><%= present_booking_price(reservable.weekday_price) %></td>
            <td><%= present_booking_price(reservable.weekend_price) %></td>
            <td><%= present_booking_price(reservable.per_person_weekday_price) %></td>
            <td><%= present_booking_price(reservable.per_person_weekend_price) %></td>
            <td>
              <%= link_to 'Edit', edit_reservable_path(reservable), class: 'btn btn-primary'%>
              <%= link_to 'Delete', reservable_path(reservable), class: 'btn btn-danger', method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/activities/edit.html.erb
<div class='row'>
  <%= render 'edit_activity_sidebar_menu', activity: @activity  %>
  <div class='col-xs-9'>
    <div class="row">
      <div class="col-xs-12">
        <center>
          <h1>Edit Activity</h1>
        </center>
      </div>
    </div>
    <div class="spacer-40"></div>
    <div class="row">
      <div class="col-xs-12">
        <%= render 'activities/activity_form' %>
      </div>
    </div>
    <br>
    <%= render 'activities/reservables_form' %>
  </div>
</div>

app/views/activities/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <center>
      <h1>
        <%= "#{@business.name}'s Activities" %>
      </h1>
    </center>
  </div>
</div>
<div class="spacer-30"></div>
<div class="row">
  <div class="col-xs-12">
    <center>
      <% if @activities.any? %>
        <table class="table">
          <thead>
            <tr>
              <th class='text-xs-center'>#</th>
              <th class='text-xs-center'>Name</th>
              <th class='text-xs-center'>Reservables</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @activities.each_with_index do |activity, index| %>
              <%- number_of_normal_reservables =
                  activity.number_of_normal_reservables %>
              <tr id="activity_<%= activity.id %>">
                <th scope="row" class='text-xs-center'>
                  <%= index + 1 %>
                </th>
                <td class='text-xs-center'>
                  <%= activity.name %>
                </td>
                <td class='text-xs-center'>
                  <%= pluralize(number_of_normal_reservables,
                      activity.reservable_type.to_s ) %>
                  <%- if number_of_normal_reservables.nonzero? %>
                    <%= pluralize(activity.number_of_party_rooms,
                        'PartyRoom' ) %>
                  <% end %>
                </td>
                <td class='text-xs-center'>
                  <div class='row'>
                    <%= link_to 'View reservations',
                      business_owner_reserver_path(activity),
                      class: 'btn btn-primary btn-sm' %>
                    <%= link_to 'View analytics',
                      view_analytics_activity_path(activity),
                      class: 'btn btn-primary btn-sm' %>
                  </div>
                  <div class='row'>
                    <%= link_to 'Edit', edit_activity_path(activity),
                      class: 'btn btn-primary btn-sm'%>
                    <%= link_to 'Delete', activity_path(activity),
                      class: 'btn btn-danger btn-sm', method: :delete %>
                  </div>
                  <div class='row'>
                    <%= link_to "Add a #{activity.reservable_type}",
                      new_activity_reservable_path(activity,
                      type: activity.reservable_type),
                      class: 'btn btn-primary btn-sm' %>
                    <%- if number_of_normal_reservables.nonzero? %>
                      <%= link_to 'Add a Party room', new_activity_reservable_path(
                        activity, type: Reservable::PARTY_ROOM_TYPE),
                        class: 'btn btn-primary btn-sm' %>
                    <% end %>
                  </div>
                  <div class="row">
                    <%= link_to 'Reservation Exports',
                      business_owner_reservations_path(activity),
                      class: 'btn btn-primary btn-sm' %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="spacer-30"></div>
        <div id='new-activity'>
          <%= link_to 'Add activity', new_business_activity_path(@business),
            class: 'btn btn-primary' %>
        </div>
      <% else %>
        <span>You haven't created any activities.</span>
        <br/>
        <%= link_to 'Create Activity', new_business_activity_path(@business) %>
      <% end %>
    </center>
  </div>
</div>

app/views/activities/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <center>
      <h1>Create Activity</h1>
    </center>
  </div>
</div>
<div class="spacer-40"></div>
<div class="row">
  <div class="col-xs-12">
    <%= render 'activities/activity_form' %>
  </div>
<div>

app/views/activities/view_analytics.html.erb
<div>
  <h4 class='text-xs-center'>
    Bookings Revenue <small>(past 60 days)</small>
  </h4>

  <% if @booking_revenues.present? %>
    <%= content_tag :canvas, '', id: 'revenueChart', data:
    {
      label: @activity.name,
      bookings: {
        dates: @booking_dates,
        revenues: @booking_revenues
      }
    } %>
  <% else  %>
    <div class='spacer-40'></div>
    <div class='alert alert-danger'>No bookings found.</div>
  <% end %>
</div>